spring:
  data:
    mongodb:
      username: debarshee
      password: debarshee
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin

server:
  port: 8090